--- 
algolia: 
  application_id: ~
  index_name: ~
  powered_by: ~
  search_only_api_key: ~
analytics: 
  google: 
    anonymize_ip: ~
    tracking_id: ~
  provider: false
atom_feed: 
  path: ~
author: 
  avatar: ~
  bio: "배워가는 학생"
  email: okht13@gmail.com
  links: 
    - 
      icon: "fas fa-fw fa-envelope-square"
      label: Email
    - 
      icon: "fas fa-fw fa-link"
      label: Website
    - 
      icon: "fab fa-fw fa-facebook-square"
      label: Facebook
    - "label:\"GitHub\" icon:\"fab fa-fw fa-github\" url:\"https://github.com/simple4logic"
    - "label:\"Instagram\" icon:\"fab fa-fw fa-instagram\""
  location: "Seoul Nat'l Univ."
  name: "Hyuntae H"
baseurl: ""
bing_site_verification: ~
category_archive: 
  path: /categories/
  type: liquid
comments: 
  discourse: 
    server: ~
  disqus: 
    shortname: ~
  facebook: 
    appid: ~
    colorscheme: ~
    num_posts: ~
  provider: ~
  staticman: 
    branch: ~
    endpoint: ~
  utterances: 
    issue_term: ~
    theme: ~
compress_html: 
  clippings: all
  ignore: 
    envs: development
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author_profile: true
      comments: ~
      layout: single
      read_time: true
      related: true
      share: true
description: "A Place for Memory."
encoding: utf-8
excerpt_separator: "\n\n"
exclude: 
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
facebook: 
  app_id: ~
  publisher: ~
  username: ~
footer: 
  links: 
    - 
      icon: "fab fa-fw fa-twitter-square"
      label: Twitter
    - 
      icon: "fab fa-fw fa-facebook-square"
      label: Facebook
    - 
      icon: "fab fa-fw fa-github"
      label: GitHub
    - 
      icon: "fab fa-fw fa-gitlab"
      label: GitLab
    - 
      icon: "fab fa-fw fa-bitbucket"
      label: Bitbucket
    - 
      icon: "fab fa-fw fa-instagram"
      label: Instagram
google: 
  instant_search: ~
  search_engine_id: ~
google_site_verification: ~
highlighter: rouge
include: 
  - .htaccess
  - _pages
incremental: false
keep_files: 
  - .git
  - .svn
kramdown: 
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
locale: ko-KR
logo: /assets/images/logo.jpg
lsi: false
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
masthead_title: ~
minimal_mistakes_skin: dark
name: "Hyuntae H"
naver_site_verification: ~
og_image: ~
paginate: 5
paginate_path: "/page:num/"
permalink: "/:categories/:title/"
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
reCaptcha: 
  secret: ~
  siteKey: ~
remote_theme: mmistakes/minimal-mistakes
repository: ~
sass: 
  sass_dir: _sass
  style: compressed
search: ~
search_full_content: ~
search_provider: ~
social: 
  links: ~
  name: ~
  type: ~
subtitle: ~
tag_archive: 
  path: /tags/
  type: liquid
teaser: ~
timezone: ~
title: Stellarium
title_separator: "-"
twitter: 
  username: ~
url: "https://simple4logic.github.io"
whitelist: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
words_per_minute: 200
yandex_site_verification: ~
